name: Jekyll build for PRs

on:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - uses: fabacab/jekyll-builder-for-github-pages-action@v1
      with:
        pre_build_commands: |
          echo Updating bundler...
          gem install bundler
